---
plugin: amazon.aws.aws_ec2
regions:
   - ap-southeast-2
filters:
  # This selects only running instances with `os` tag set to `nix`.
  tag:os: nix
  instance-state-name : running
keyed_groups:
  - key: tags
    prefix: tag
aws_access_key_id: ""
aws_secret_access_key: ""
