---
# task file to install required package

- name: Install python3-pip and pexpect dependency
  ansible.builtin.yum:
    name:
      - python3-pip
      - python3-pexpect
    state: latest
  tags: install_dependency
  register: dependency_status
