---
# tasks file for Elastic Agent upgrade

- name: Upgrading Elastic Agent from "{{ agent_version }}" to "{{ agent_upgrade_version }}"
  ansible.builtin.command: ./elastic-agent upgrade "{{ agent_upgrade_version }}" --pgp-uri "{{ agent_pgp_key }}"
  args:
    chdir: "{{ agent_install_dir }}"
  tags: upgrade
  timeout: 300
  register: upgrade_status
- debug:
    var: upgrade_status
